config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/ibergrid-perf-essay:
      branch: main
      repo: https://github.com/EOSC-synergy/ibergrid-perf-essay
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/ibergrid-perf-essay git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-moth.sh
        container: qc.acc_lanky-purple-peccary
  QC.Doc:
    repos:
      github.com/EOSC-synergy/ibergrid-perf-essay find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-puce-buffalo.sh
        container: qc.doc_tacky-tomato-ocelot
      github.com/EOSC-synergy/ibergrid-perf-essay git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-pumpkin-buzzard.sh
        container: qc.doc_sunny-pear-dog
  QC.Lic:
    repos:
      github.com/EOSC-synergy/ibergrid-perf-essay licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-puce-mau.sh
        container: qc.lic_seedy-burgundy-terrier
  QC.Ver:
    repos:
      github.com/EOSC-synergy/ibergrid-perf-essay get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-aquamarine-kakapo.sh
        container: qc.ver_wimpy-pink-slug
timeout: 5400
